package com.teoware.refapp.dao.util;

import com.teoware.refapp.model.common.Id;
import com.teoware.refapp.testtools.JavaBeanTester;
import java.beans.IntrospectionException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import org.junit.Test;

public class ChangeResultTest {

    @Test
    public void testDefaultConstructor() {
        ChangeResult result = new ChangeResult();

        assertNotNull(result);
        assertEquals(0, result.getRowsAffected());
        assertNull(result.getAutoGeneratedKey());
    }

    @Test
    public void testOneFieldConstructor() {
        ChangeResult result = new ChangeResult(2);

        assertNotNull(result);
        assertEquals(2, result.getRowsAffected());
        assertNull(result.getAutoGeneratedKey());
    }

    @Test
    public void testTwoFieldConstructor() {
        ChangeResult result = new ChangeResult(3, new Id(4L));

        assertNotNull(result);
        assertEquals(3, result.getRowsAffected());
        assertNotNull(result.getAutoGeneratedKey());
        assertEquals(4, result.getAutoGeneratedKey().getId().intValue());
    }

    @Test
    public void testBean() throws IntrospectionException {
        JavaBeanTester.test(ChangeResult.class);
    }
}
