-- Clean tables

DROP TABLE REFAPP.TASKS_STATUS;

DROP TABLE REFAPP.TASKS;

DROP TABLE REFAPP.NOTES_STATUS;

DROP TABLE REFAPP.NOTES;

DROP TABLE REFAPP.AUTHOR_STATUS;

DROP TABLE REFAPP.AUTHOR_PASSWORD;

DROP TABLE REFAPP.AUTHOR;
