package com.teoware.refapp.dao.util;

import java.math.BigInteger;

public class ChangeResult {

	private int rowsAffected;
	private BigInteger autoGeneratedKey;

	public ChangeResult() {
	}

	public ChangeResult(int rowsAffected) {
		this.rowsAffected = rowsAffected;
	}

	public ChangeResult(int rowsAffected, BigInteger autoGeneratedKey) {
		this.rowsAffected = rowsAffected;
		this.autoGeneratedKey = autoGeneratedKey;
	}

	public int getRowsAffected() {
		return rowsAffected;
	}

	public void setRowsAffected(int rowsAffected) {
		this.rowsAffected = rowsAffected;
	}

	public BigInteger getAutoGeneratedKey() {
		return autoGeneratedKey;
	}

	public void setAutoGeneratedKey(BigInteger autoGeneratedKey) {
		this.autoGeneratedKey = autoGeneratedKey;
	}
}
