-- Table definitions

CREATE TABLE REFAPP.TASKS
(
	ID			VARCHAR(50) NOT NULL,
	AUTHOR		VARCHAR(20) NOT NULL,
	TITLE		VARCHAR(100) NOT NULL,
	TASK		VARCHAR(300),
	CONSTRAINT TASKS_PK		PRIMARY KEY (ID),
	CONSTRAINT TASKS_FK1	FOREIGN KEY (AUTHOR) REFERENCES REFAPP.AUTHOR (USERNAME) ON DELETE CASCADE
);

CREATE TABLE REFAPP.TASKS_STATUS
(
	ID			VARCHAR(50) NOT NULL,
	STATUS		VARCHAR(10) NOT NULL,
	CREATED		DATE NOT NULL,
	MODIFIED	DATE NOT NULL,
	CONSTRAINT TASKS_STATUS_PK	PRIMARY KEY (ID),
	CONSTRAINT TASKS_STATUS_FK1	FOREIGN KEY (STATUS) REFERENCES REFAPP.REF_TASKS_STATUS (STATUS),
	CONSTRAINT TASKS_STATUS_CC1	CHECK (MODIFIED >= CREATED)
);
