-- View definitions

CREATE VIEW REFAPP.AUTHOR_V
(USERNAME, REALNAME, EMAIL, STATUS, CREATED, MODIFIED)
AS SELECT A.USERNAME, A.REALNAME, A.EMAIL, S.STATUS, S.CREATED, S.MODIFIED FROM REFAPP.AUTHOR A, REFAPP.AUTHOR_STATUS S WHERE A.USERNAME = S.AUTHOR;

CREATE VIEW REFAPP.NOTES_V
(AUTHOR, TITLE, NOTE, STATUS, CREATED, MODIFIED)
AS SELECT N.AUTHOR, N.TITLE, N.NOTE, S.STATUS, S.CREATED, S.MODIFIED FROM REFAPP.NOTES N, REFAPP.NOTES_STATUS S WHERE N.ID = S.ID;

CREATE VIEW REFAPP.TASKS_V
(AUTHOR, TITLE, TASK, STATUS, CREATED, MODIFIED)
AS SELECT T.AUTHOR, T.TITLE, T.TASK, S.STATUS, S.CREATED, S.MODIFIED FROM REFAPP.TASKS T, REFAPP.TASKS_STATUS S WHERE T.ID = S.ID;
