package com.teoware.refapp.dao.util;

import com.teoware.refapp.model.common.Id;

public class ChangeResult {

    private int rowsAffected;
    private Id autoGeneratedKey;

    public ChangeResult() {
    }

    public ChangeResult(int rowsAffected) {
        this.rowsAffected = rowsAffected;
    }

    public ChangeResult(int rowsAffected, Id autoGeneratedKey) {
        this.rowsAffected = rowsAffected;
        this.autoGeneratedKey = autoGeneratedKey;
    }

    public int getRowsAffected() {
        return rowsAffected;
    }

    public void setRowsAffected(int rowsAffected) {
        this.rowsAffected = rowsAffected;
    }

    public Id getAutoGeneratedKey() {
        return autoGeneratedKey;
    }

    public void setAutoGeneratedKey(Id autoGeneratedKey) {
        this.autoGeneratedKey = autoGeneratedKey;
    }
}
