INSERT INTO APP.REF_AUTHOR_STATUS VALUES ('PENDING', 'User is pending activation');
INSERT INTO APP.REF_AUTHOR_STATUS VALUES ('ACTIVE', 'User is active');
INSERT INTO APP.REF_AUTHOR_STATUS VALUES ('SUSPENDED', 'User is suspended');
INSERT INTO APP.REF_AUTHOR_STATUS VALUES ('DELETED', 'User has been deleted');

INSERT INTO APP.REF_NOTES_STATUS VALUES ('NEW', 'New note');
INSERT INTO APP.REF_NOTES_STATUS VALUES ('MODIFIED', 'Note was modified');
INSERT INTO APP.REF_NOTES_STATUS VALUES ('DELETED', 'Note was deleted');

INSERT INTO APP.AUTHOR VALUES ('thomas', 'Thomas', 'thomas@tow.no');

INSERT INTO APP.AUTHOR_STATUS VALUES ('thomas', 'ACTIVE', CURRENT_DATE, CURRENT_DATE);

INSERT INTO APP.NOTES VALUES ('aaaaa', 'thomas', 'This is a new note', 'Blah blah...');

INSERT INTO APP.NOTES_STATUS VALUES ('aaaaa', 'NEW', CURRENT_DATE, CURRENT_DATE);