-- Ref table definitions

CREATE TABLE APP.REF_AUTHOR_STATUS
(
	STATUS		VARCHAR(10) NOT NULL,
	DESCRIPTION	VARCHAR(50) NOT NULL,
	CONSTRAINT REF_AUTHOR_STATUS_UC UNIQUE (STATUS)
);

CREATE TABLE APP.REF_NOTES_STATUS
(
	STATUS		VARCHAR(10) NOT NULL,
	DESCRIPTION	VARCHAR(50) NOT NULL,
	CONSTRAINT REF_NOTES_STATUS_UC UNIQUE (STATUS)
);
