-- Ref table definitions

CREATE TABLE REFAPP.REF_USERS_STATUS
(
	STATUS		VARCHAR(10) NOT NULL,
	DESCRIPTION	VARCHAR(50) NOT NULL,
	CONSTRAINT REF_USERS_STATUS_UC1 UNIQUE (STATUS)
);

CREATE TABLE REFAPP.REF_NOTES_STATUS
(
	STATUS		VARCHAR(10) NOT NULL,
	DESCRIPTION	VARCHAR(50) NOT NULL,
	CONSTRAINT REF_NOTES_STATUS_UC1 UNIQUE (STATUS)
);

CREATE TABLE REFAPP.REF_TASKS_STATUS
(
	STATUS		VARCHAR(10) NOT NULL,
	DESCRIPTION	VARCHAR(50) NOT NULL,
	CONSTRAINT REF_TASKS_STATUS_UC1 UNIQUE (STATUS)
);

CREATE TABLE REFAPP.REF_GENDER
(
	GENDER		VARCHAR(10) NOT NULL,
	DESCRIPTION	VARCHAR(50) NOT NULL,
	CONSTRAINT REF_GENDER_UC1 UNIQUE (GENDER)
);
