-- Table definitions

CREATE TABLE REFAPP.USERS
(
	USERNAME	VARCHAR(20) NOT NULL,
	FIRSTNAME	VARCHAR(50) NOT NULL,
	LASTNAME	VARCHAR(50) NOT NULL,
	BIRTHDATE	DATE NOT NULL,
	GENDER		VARCHAR(10) NOT NULL,
	EMAIL		VARCHAR(50) NOT NULL,
	PHONE		VARCHAR(50),
	CONSTRAINT USERS_PK		PRIMARY KEY (USERNAME),
	CONSTRAINT USERS_FK1	FOREIGN KEY (GENDER) REFERENCES REFAPP.REF_GENDER (GENDER),
	CONSTRAINT USERS_UC1	UNIQUE (EMAIL)
);

CREATE TABLE REFAPP.USERS_STATUS
(
	USERNAME	VARCHAR(20) NOT NULL,
	STATUS		VARCHAR(10) NOT NULL,
	CREATED		TIMESTAMP NOT NULL,
	MODIFIED	TIMESTAMP NOT NULL,
	CONSTRAINT USERS_STATUS_PK	PRIMARY KEY (USERNAME),
	CONSTRAINT USERS_STATUS_FK1	FOREIGN KEY (USERNAME) REFERENCES REFAPP.USERS (USERNAME) ON DELETE CASCADE,
	CONSTRAINT USERS_STATUS_FK2	FOREIGN KEY (STATUS) REFERENCES REFAPP.REF_USERS_STATUS (STATUS),
	CONSTRAINT USERS_STATUS_CC1	CHECK (MODIFIED >= CREATED)
);

CREATE TABLE REFAPP.USERS_PASSWORD
(
	USERNAME	VARCHAR(20) NOT NULL,
	PASSWORD	VARCHAR(100) NOT NULL,
	SALT		VARCHAR(100) NOT NULL,
	CONSTRAINT USERS_PASSWORD_PK	PRIMARY KEY (USERNAME),
	CONSTRAINT USERS_PASSWORD_FK1	FOREIGN KEY (USERNAME) REFERENCES REFAPP.USERS (USERNAME) ON DELETE CASCADE
);

CREATE TABLE REFAPP.USERS_ADDRESS
(
	USERNAME		VARCHAR(20) NOT NULL,
	ADDRESS			VARCHAR(50),
	POSTALCODE		VARCHAR(10),
	MUNICIPALITY	VARCHAR(50),
	REGION			VARCHAR(50),
	COUNTRY			VARCHAR(50),
	CONSTRAINT USERS_ADDRESS_PK		PRIMARY KEY (USERNAME),
	CONSTRAINT USERS_ADDRESS_FK1	FOREIGN KEY (USERNAME) REFERENCES REFAPP.USERS (USERNAME) ON DELETE CASCADE
);
