-- Table definitions

CREATE TABLE REFAPP.GROUPS
(
	ID				BIGINT				GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	GROUPNAME		VARCHAR(20)			NOT NULL,
	DESCRIPTION		VARCHAR(100)		,
	CONSTRAINT		GROUPS_PK			PRIMARY KEY (ID),
	CONSTRAINT		GROUPS_UC1			UNIQUE (GROUPNAME)
);

CREATE TABLE REFAPP.GROUP_LINK
(
	ID				BIGINT				GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	GROUP_ID		BIGINT				NOT NULL,
	USER_ID			BIGINT				NOT NULL,
	CONSTRAINT		GROUP_LINK_PK		PRIMARY KEY (ID),
	CONSTRAINT		GROUP_LINK_FK1		FOREIGN KEY (GROUP_ID) REFERENCES REFAPP.GROUPS (ID) ON DELETE CASCADE,
	CONSTRAINT		GROUP_LINK_FK2		FOREIGN KEY (USER_ID) REFERENCES REFAPP.USERS (ID) ON DELETE CASCADE
);
