-- Table definitions

CREATE TABLE REFAPP.NOTES
(
	ID			VARCHAR(50) NOT NULL,
	AUTHOR		VARCHAR(20) NOT NULL,
	TITLE		VARCHAR(100) NOT NULL,
	NOTE		VARCHAR(300),
	CONSTRAINT NOTES_PK		PRIMARY KEY (ID),
	CONSTRAINT NOTES_FK1	FOREIGN KEY (AUTHOR) REFERENCES REFAPP.AUTHORS (USERNAME) ON DELETE CASCADE
);

CREATE TABLE REFAPP.NOTES_STATUS
(
	ID			VARCHAR(50) NOT NULL,
	STATUS		VARCHAR(10) NOT NULL,
	CREATED		DATE NOT NULL,
	MODIFIED	DATE NOT NULL,
	CONSTRAINT NOTES_STATUS_PK	PRIMARY KEY (ID),
	CONSTRAINT NOTES_STATUS_FK1	FOREIGN KEY (STATUS) REFERENCES REFAPP.REF_NOTES_STATUS (STATUS),
	CONSTRAINT NOTES_STATUS_CC1	CHECK (MODIFIED >= CREATED)
);
