-- Table definitions

CREATE TABLE REFAPP.TASKS
(
	ID			BIGINT			GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	USER_ID		BIGINT			NOT NULL,
	TITLE		VARCHAR(100)	NOT NULL,
	TASK		VARCHAR(300),
	CONSTRAINT	TASKS_PK		PRIMARY KEY (ID),
	CONSTRAINT	TASKS_FK1		FOREIGN KEY (USER_ID) REFERENCES REFAPP.USERS (ID) ON DELETE CASCADE
);

CREATE TABLE REFAPP.TASK_STATUS
(
	ID			BIGINT				GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	TASK_ID		BIGINT				NOT NULL,
	STATUS		VARCHAR(10)			NOT NULL,
	CREATED		TIMESTAMP			NOT NULL,
	MODIFIED	TIMESTAMP			NOT NULL,
	CONSTRAINT	TASK_STATUS_PK		PRIMARY KEY (ID),
	CONSTRAINT	TASK_STATUS_FK1		FOREIGN KEY (TASK_ID) REFERENCES REFAPP.TASKS (ID),
	CONSTRAINT	TASK_STATUS_FK2		FOREIGN KEY (STATUS) REFERENCES REFAPP.REF_TASK_STATUS (STATUS),
	CONSTRAINT	TASK_STATUS_CC1		CHECK (MODIFIED >= CREATED)
);
