-- Trigger definitions

CREATE TRIGGER REFAPP.USERS_TRG1
	AFTER INSERT ON REFAPP.USERS
	REFERENCING NEW AS NEWROW
	FOR EACH ROW MODE DB2SQL
		INSERT INTO REFAPP.USERS_STATUS (USERNAME, STATUS, CREATED, MODIFIED)
		VALUES (NEWROW.USERNAME, 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;

CREATE TRIGGER REFAPP.USERS_TRG2
	AFTER UPDATE ON REFAPP.USERS
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.USERS_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE USERNAME = OLDROW.USERNAME
;

CREATE TRIGGER REFAPP.USERS_STATUS_TRG1
	AFTER UPDATE OF STATUS ON REFAPP.USERS_STATUS
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.USERS_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE USERNAME = OLDROW.USERNAME
;

CREATE TRIGGER REFAPP.USERS_PASSWORD_TRG1
	AFTER UPDATE ON REFAPP.USERS_PASSWORD
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.USERS_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE USERNAME = OLDROW.USERNAME
;

CREATE TRIGGER REFAPP.USERS_ADDRESS_TRG1
	AFTER UPDATE ON REFAPP.USERS_ADDRESS
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.USERS_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE USERNAME = OLDROW.USERNAME
;
