-- Trigger definitions

CREATE TRIGGER REFAPP.AUTHORS_TRG01
	AFTER INSERT ON REFAPP.AUTHORS
	REFERENCING NEW AS NEWROW
	FOR EACH ROW MODE DB2SQL
		INSERT INTO REFAPP.AUTHORS_STATUS (AUTHOR, STATUS, CREATED, MODIFIED)
		VALUES (NEWROW.USERNAME, 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;

CREATE TRIGGER REFAPP.AUTHORS_TRG02
	AFTER UPDATE ON REFAPP.AUTHORS
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.AUTHORS_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE AUTHOR = OLDROW.USERNAME
;

CREATE TRIGGER REFAPP.AUTHORS_STATUS_TRG
	AFTER UPDATE OF STATUS ON REFAPP.AUTHORS_STATUS
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.AUTHORS_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE AUTHOR = OLDROW.AUTHOR
;

CREATE TRIGGER REFAPP.AUTHORS_PASSWORD_TRG
	AFTER UPDATE ON REFAPP.AUTHORS_PASSWORD
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.AUTHORS_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE AUTHOR = OLDROW.AUTHOR
;

CREATE TRIGGER REFAPP.AUTHORS_ADDRESS_TRG
	AFTER UPDATE ON REFAPP.AUTHORS_ADDRESS
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.AUTHORS_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE AUTHOR = OLDROW.AUTHOR
;
