-- Trigger definitions

--CREATE TRIGGER REFAPP.AUTHOR_STATUS_TR
--AFTER INSERT ON REFAPP.AUTHOR_STATUS
--FOR EACH ROW MODE DB2SQL
--INSERT INTO REFAPP.AUTHOR_STATUS (CREATED, MODIFIED) VALUES (CURRENT_DATE, CURRENT_DATE);
