-- Trigger definitions

CREATE TRIGGER REFAPP.USERS_TRG1
	AFTER INSERT ON REFAPP.USERS
	REFERENCING NEW AS NEWROW
	FOR EACH ROW MODE DB2SQL
		INSERT INTO REFAPP.USER_STATUS (USER_ID, STATUS, CREATED, MODIFIED)
		VALUES (NEWROW.ID, 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;

CREATE TRIGGER REFAPP.USERS_TRG2
	AFTER UPDATE ON REFAPP.USERS
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.USER_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE USER_ID = OLDROW.ID
;

CREATE TRIGGER REFAPP.USER_INFO_TRG1
	AFTER UPDATE ON REFAPP.USER_INFO
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.USER_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE USER_ID = OLDROW.ID
;

CREATE TRIGGER REFAPP.USER_STATUS_TRG1
	AFTER UPDATE OF STATUS ON REFAPP.USER_STATUS
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.USER_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE USER_ID = OLDROW.USER_ID
;

CREATE TRIGGER REFAPP.USER_PASSWORD_TRG1
	AFTER UPDATE ON REFAPP.USER_PASSWORD
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.USER_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE USER_ID = OLDROW.USER_ID
;

CREATE TRIGGER REFAPP.USER_ADDRESS_TRG1
	AFTER UPDATE ON REFAPP.USER_ADDRESS
	REFERENCING OLD AS OLDROW
	FOR EACH ROW MODE DB2SQL
		UPDATE REFAPP.USER_STATUS SET MODIFIED = CURRENT_TIMESTAMP
		WHERE USER_ID = OLDROW.USER_ID
;
