-- View definitions

CREATE VIEW REFAPP.USERS_V
(USERNAME, FIRSTNAME, LASTNAME, BIRTHDATE, GENDER, EMAIL, PHONE,
ADDRESS, POSTALCODE, MUNICIPALITY, REGION, COUNTRY, STATUS, CREATED, MODIFIED)
AS SELECT U.USERNAME, U.FIRSTNAME, U.LASTNAME, U.BIRTHDATE, U.GENDER, U.EMAIL, U.PHONE,
D.ADDRESS, D.POSTALCODE, D.MUNICIPALITY, D.REGION, D.COUNTRY, S.STATUS, S.CREATED, S.MODIFIED
FROM REFAPP.USERS U, REFAPP.USERS_ADDRESS D, REFAPP.USERS_STATUS S
WHERE U.USERNAME = S.USERNAME AND U.USERNAME = D.USERNAME;

CREATE VIEW REFAPP.NOTES_V
(USERNAME, TITLE, NOTE, STATUS, CREATED, MODIFIED)
AS SELECT N.USERNAME, N.TITLE, N.NOTE, S.STATUS, S.CREATED, S.MODIFIED FROM REFAPP.NOTES N, REFAPP.NOTES_STATUS S WHERE N.ID = S.ID;

CREATE VIEW REFAPP.TASKS_V
(USERNAME, TITLE, TASK, STATUS, CREATED, MODIFIED)
AS SELECT T.USERNAME, T.TITLE, T.TASK, S.STATUS, S.CREATED, S.MODIFIED FROM REFAPP.TASKS T, REFAPP.TASKS_STATUS S WHERE T.ID = S.ID;
