-- View definitions

CREATE VIEW REFAPP.USERS_V
(USERNAME, FIRSTNAME, LASTNAME, BIRTHDATE, GENDER, EMAIL, PHONE,
ADDRESS, POSTALCODE, MUNICIPALITY, REGION, COUNTRY, STATUS, CREATED, MODIFIED)
AS SELECT U.USERNAME, D.FIRSTNAME, D.LASTNAME, D.BIRTHDATE, D.GENDER, D.EMAIL, D.PHONE,
A.ADDRESS, A.POSTALCODE, A.MUNICIPALITY, A.REGION, A.COUNTRY, S.STATUS, S.CREATED, S.MODIFIED
FROM REFAPP.USERS U, REFAPP.USER_DETAILS D, REFAPP.USER_ADDRESS A, REFAPP.USER_STATUS S
WHERE U.ID = D.USER_ID AND U.ID = S.USER_ID AND U.ID = A.USER_ID;

CREATE VIEW REFAPP.NOTES_V
(TITLE, DESCRIPTION, STATUS, CREATED, MODIFIED)
AS SELECT N.TITLE, D.DESCRIPTION, S.STATUS, S.CREATED, S.MODIFIED
FROM REFAPP.NOTES N, REFAPP.NOTE_DETAILS D, REFAPP.NOTE_STATUS S
WHERE N.ID = D.NOTE_ID AND N.ID = S.NOTE_ID;

CREATE VIEW REFAPP.TASKS_V
(TITLE, DESCRIPTION, STATUS, CREATED, MODIFIED)
AS SELECT T.TITLE, D.DESCRIPTION, S.STATUS, S.CREATED, S.MODIFIED
FROM REFAPP.TASKS T, REFAPP.TASK_DETAILS D, REFAPP.TASK_STATUS S
WHERE T.ID = D.TASK_ID AND T.ID = S.TASK_ID;
