-- View definitions

CREATE VIEW REFAPP.AUTHORS_V
(USERNAME, FIRSTNAME, LASTNAME, BIRTHDATE, GENDER, EMAIL, PHONE,
ADDRESS, POSTALCODE, MUNICIPALITY, REGION, COUNTRY, STATUS, CREATED, MODIFIED)
AS SELECT A.USERNAME, A.FIRSTNAME, A.LASTNAME, A.BIRTHDATE, A.GENDER, A.EMAIL, A.PHONE,
D.ADDRESS, D.POSTALCODE, D.MUNICIPALITY, D.REGION, D.COUNTRY, S.STATUS, S.CREATED, S.MODIFIED
FROM REFAPP.AUTHORS A, REFAPP.AUTHORS_ADDRESS D, REFAPP.AUTHORS_STATUS S
WHERE A.USERNAME = S.AUTHOR AND A.USERNAME = D.AUTHOR;

CREATE VIEW REFAPP.NOTES_V
(AUTHOR, TITLE, NOTE, STATUS, CREATED, MODIFIED)
AS SELECT N.AUTHOR, N.TITLE, N.NOTE, S.STATUS, S.CREATED, S.MODIFIED FROM REFAPP.NOTES N, REFAPP.NOTES_STATUS S WHERE N.ID = S.ID;

CREATE VIEW REFAPP.TASKS_V
(AUTHOR, TITLE, TASK, STATUS, CREATED, MODIFIED)
AS SELECT T.AUTHOR, T.TITLE, T.TASK, S.STATUS, S.CREATED, S.MODIFIED FROM REFAPP.TASKS T, REFAPP.TASKS_STATUS S WHERE T.ID = S.ID;
