package com.teoware.refapp.dao.test;

public interface TestDataSourceMetaData {

	static final String CREATE_SCHEMA_REFAPP_STATEMENT = "CREATE SCHEMA REFAPP AUTHORIZATION DBA";

	static final String SELECT_SCHEMA_REFAPP_STATEMENT = "SELECT SCHEMA_NAME FROM "
			+ "INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'REFAPP'";

	static final String CREATE_TABLE_REF_USER_STATUS_STATEMENT = "CREATE TABLE REFAPP.REF_USER_STATUS ("
			+ "STATUS VARCHAR(10) NOT NULL, " + "DESCRIPTION VARCHAR(50) NOT NULL, "
			+ "CONSTRAINT REF_USER_STATUS_UC UNIQUE (STATUS))";

	static final String CREATE_TABLE_REF_NOTE_STATUS_STATEMENT = "CREATE TABLE REFAPP.REF_NOTE_STATUS ("
			+ "STATUS VARCHAR(10) NOT NULL, " + "DESCRIPTION VARCHAR(50) NOT NULL, "
			+ "CONSTRAINT REF_NOTE_STATUS_UC UNIQUE (STATUS))";

	static final String CREATE_TABLE_REF_TASK_STATUS_STATEMENT = "CREATE TABLE REFAPP.REF_TASK_STATUS ("
			+ "STATUS VARCHAR(10) NOT NULL, " + "DESCRIPTION VARCHAR(50) NOT NULL, "
			+ "CONSTRAINT REF_TASK_STATUS_UC UNIQUE (STATUS))";

	static final String CREATE_TABLE_REF_GENDER_STATEMENT = "CREATE TABLE REFAPP.REF_GENDER ("
			+ "GENDER VARCHAR(10) NOT NULL, " + "DESCRIPTION VARCHAR(50) NOT NULL, "
			+ "CONSTRAINT REF_GENDER_UC UNIQUE (GENDER))";

	static final String CREATE_TABLE_USERS_STATEMENT = "CREATE TABLE REFAPP.USERS ("
			+ "ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
			+ "USERNAME VARCHAR(20) NOT NULL, " + "CONSTRAINT USERS_PK PRIMARY KEY (ID), "
			+ "CONSTRAINT USERS_UC1 UNIQUE (USERNAME))";

	static final String CREATE_TABLE_USER_DETAILS_STATEMENT = "CREATE TABLE REFAPP.USER_DETAILS ("
			+ "ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
			+ "USER_ID BIGINT NOT NULL, " + "FIRSTNAME VARCHAR(50) NOT NULL, " + "LASTNAME VARCHAR(50) NOT NULL, "
			+ "BIRTHDATE DATE NOT NULL, " + "GENDER VARCHAR(10) NOT NULL, " + "EMAIL VARCHAR(50) NOT NULL, "
			+ "PHONE VARCHAR(50), " + "CONSTRAINT USER_DETAILS_PK PRIMARY KEY (ID), "
			+ "CONSTRAINT USER_DETAILS_FK1 FOREIGN KEY (USER_ID) REFERENCES REFAPP.USERS (ID) ON DELETE CASCADE, "
			+ "CONSTRAINT USER_DETAILS_FK2 FOREIGN KEY (GENDER) REFERENCES REFAPP.REF_GENDER (GENDER), "
			+ "CONSTRAINT USER_DETAILS_UC1 UNIQUE (EMAIL))";

	static final String CREATE_TABLE_USER_STATUS_STATEMENT = "CREATE TABLE REFAPP.USER_STATUS ("
			+ "ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
			+ "USER_ID BIGINT NOT NULL, " + "STATUS VARCHAR(10) NOT NULL, " + "CREATED TIMESTAMP NOT NULL, "
			+ "MODIFIED	TIMESTAMP NOT NULL, " + "CONSTRAINT USER_STATUS_PK PRIMARY KEY (ID), "
			+ "CONSTRAINT USER_STATUS_FK1 FOREIGN KEY (USER_ID) REFERENCES REFAPP.USERS (ID) ON DELETE CASCADE, "
			+ "CONSTRAINT USER_STATUS_FK2 FOREIGN KEY (STATUS) REFERENCES REFAPP.REF_USER_STATUS (STATUS), "
			+ "CONSTRAINT USER_STATUS_CC1 CHECK (MODIFIED >= CREATED))";

	static final String CREATE_TABLE_USER_PASSWORD_STATEMENT = "CREATE TABLE REFAPP.USER_PASSWORD ("
			+ "ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
			+ "USER_ID BIGINT NOT NULL, " + "PASSWORD	VARCHAR(100) NOT NULL, " + "SALT	VARCHAR(100) NOT NULL, "
			+ "CONSTRAINT USER_PASSWORD_PK PRIMARY KEY (ID), "
			+ "CONSTRAINT USER_PASSWORD_FK1 FOREIGN KEY (USER_ID) REFERENCES REFAPP.USERS (ID) ON DELETE CASCADE)";

	static final String CREATE_TABLE_USER_ADDRESS_STATEMENT = "CREATE TABLE REFAPP.USER_ADDRESS ("
			+ "ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
			+ "USER_ID BIGINT NOT NULL, " + "ADDRESS VARCHAR(50), " + "POSTALCODE VARCHAR(10), "
			+ "MUNICIPALITY VARCHAR(50), " + "REGION VARCHAR(50), " + "COUNTRY VARCHAR(50), "
			+ "CONSTRAINT USER_ADDRESS_PK PRIMARY KEY (ID), "
			+ "CONSTRAINT USER_ADDRESS_FK1 FOREIGN KEY (USER_ID) REFERENCES REFAPP.USERS (ID) ON DELETE CASCADE)";

	static final String CREATE_VIEW_USERS_V_STATEMENT = "CREATE VIEW REFAPP.USERS_V ("
			+ "USERNAME, FIRSTNAME, LASTNAME, BIRTHDATE, GENDER, EMAIL, PHONE, "
			+ "ADDRESS, POSTALCODE, MUNICIPALITY, REGION, COUNTRY, STATUS, CREATED, MODIFIED) "
			+ "AS SELECT U.USERNAME, D.FIRSTNAME, D.LASTNAME, D.BIRTHDATE, D.GENDER, D.EMAIL, D.PHONE, "
			+ "A.ADDRESS, A.POSTALCODE, A.MUNICIPALITY, A.REGION, A.COUNTRY, S.STATUS, S.CREATED, S.MODIFIED "
			+ "FROM REFAPP.USERS U, REFAPP.USER_DETAILS D, REFAPP.USER_ADDRESS A, REFAPP.USER_STATUS S "
			+ "WHERE U.ID = D.USER_ID AND U.ID = S.USER_ID AND U.ID = A.USER_ID";

	static final String CREATE_TRIGGER_USERS_TRG1_STATEMENT = "CREATE TRIGGER REFAPP.USERS_TRG1 "
			+ "AFTER INSERT ON REFAPP.USERS REFERENCING NEW ROW AS NEWROW FOR EACH ROW BEGIN ATOMIC "
			+ "INSERT INTO REFAPP.USER_STATUS (USER_ID, STATUS, CREATED, MODIFIED) "
			+ "VALUES (NEWROW.ID, 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); END";

	static final String CREATE_TRIGGER_USERS_TRG2_STATEMENT = "CREATE TRIGGER REFAPP.USERS_TRG2 "
			+ "AFTER UPDATE ON REFAPP.USERS REFERENCING OLD ROW AS OLDROW FOR EACH ROW BEGIN ATOMIC "
			+ "UPDATE REFAPP.USER_STATUS SET MODIFIED = CURRENT_TIMESTAMP WHERE USER_ID = OLDROW.ID; END";

	static final String CREATE_TRIGGER_USER_DETAILS_TRG1_STATEMENT = "CREATE TRIGGER REFAPP.USER_DETAILS_TRG1 "
			+ "AFTER UPDATE ON REFAPP.USER_DETAILS REFERENCING OLD ROW AS OLDROW FOR EACH ROW BEGIN ATOMIC "
			+ "UPDATE REFAPP.USER_STATUS SET MODIFIED = CURRENT_TIMESTAMP WHERE USER_ID = OLDROW.USER_ID; END";

	static final String CREATE_TRIGGER_USER_PASSWORD_TRG1_STATEMENT = "CREATE TRIGGER REFAPP.USER_PASSWORD_TRG1 "
			+ "AFTER UPDATE ON REFAPP.USER_PASSWORD REFERENCING OLD ROW AS OLDROW FOR EACH ROW BEGIN ATOMIC "
			+ "UPDATE REFAPP.USER_STATUS SET MODIFIED = CURRENT_TIMESTAMP WHERE USER_ID = OLDROW.USER_ID; END";

	static final String CREATE_TRIGGER_USER_ADDRESS_TRG1_STATEMENT = "CREATE TRIGGER REFAPP.USER_ADDRESS_TRG1 "
			+ "AFTER UPDATE ON REFAPP.USER_ADDRESS REFERENCING OLD ROW AS OLDROW FOR EACH ROW BEGIN ATOMIC "
			+ "UPDATE REFAPP.USER_STATUS SET MODIFIED = CURRENT_TIMESTAMP WHERE USER_ID = OLDROW.USER_ID; END";

	static final String CREATE_TRIGGER_USER_STATUS_TRG1_STATEMENT = "CREATE TRIGGER REFAPP.USER_STATUS_TRG1 "
			+ "AFTER UPDATE OF STATUS ON REFAPP.USER_STATUS REFERENCING OLD ROW AS OLDROW FOR EACH ROW BEGIN ATOMIC "
			+ "UPDATE REFAPP.USER_STATUS SET MODIFIED = CURRENT_TIMESTAMP WHERE USER_ID = OLDROW.USER_ID; END";

	static final String CREATE_TABLE_NOTES_STATEMENT = "CREATE TABLE REFAPP.NOTES ("
			+ "ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
			+ "USER_ID BIGINT NOT NULL, " + "UUID VARCHAR(36) NOT NULL, " + "CONSTRAINT NOTES_PK PRIMARY KEY (ID), "
			+ "CONSTRAINT NOTES_FK1 FOREIGN KEY (USER_ID) REFERENCES REFAPP.USERS (ID) ON DELETE CASCADE, "
			+ "CONSTRAINT NOTES_UC1 UNIQUE (UUID))";

	static final String CREATE_TABLE_NOTE_DETAILS_STATEMENT = "CREATE TABLE REFAPP.NOTE_DETAILS ("
			+ "ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
			+ "NOTE_ID BIGINT NOT NULL, " + "TITLE VARCHAR(100) NOT NULL, " + "DESCRIPTION VARCHAR(100), "
			+ "CONSTRAINT NOTE_DETAILS_PK PRIMARY KEY (ID), "
			+ "CONSTRAINT NOTE_DETAILS_FK1 FOREIGN KEY (NOTE_ID) REFERENCES REFAPP.NOTES (ID) ON DELETE CASCADE)";

	static final String CREATE_TABLE_NOTE_STATUS_STATEMENT = "CREATE TABLE REFAPP.NOTE_STATUS ("
			+ "ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
			+ "NOTE_ID BIGINT NOT NULL, " + "STATUS VARCHAR(10) NOT NULL, " + "CREATED TIMESTAMP NOT NULL, "
			+ "MODIFIED	TIMESTAMP NOT NULL, " + "CONSTRAINT NOTE_STATUS_PK PRIMARY KEY (ID), "
			+ "CONSTRAINT NOTE_STATUS_FK1 FOREIGN KEY (NOTE_ID) REFERENCES REFAPP.NOTES (ID) ON DELETE CASCADE, "
			+ "CONSTRAINT NOTE_STATUS_FK2 FOREIGN KEY (STATUS) REFERENCES REFAPP.REF_NOTE_STATUS (STATUS), "
			+ "CONSTRAINT NOTE_STATUS_CC1 CHECK (MODIFIED >= CREATED))";

	static final String CREATE_VIEW_NOTES_V_STATEMENT = "CREATE VIEW REFAPP.NOTES_V "
			+ "(UUID, TITLE, DESCRIPTION, STATUS, CREATED, MODIFIED) "
			+ "AS SELECT N.UUID, D.TITLE, D.DESCRIPTION, S.STATUS, S.CREATED, S.MODIFIED "
			+ "FROM REFAPP.NOTES N, REFAPP.NOTE_DETAILS D, REFAPP.NOTE_STATUS S "
			+ "WHERE N.ID = D.NOTE_ID AND N.ID = S.NOTE_ID";

	static final String CREATE_TRIGGER_NOTES_TRG1_STATEMENT = "CREATE TRIGGER REFAPP.NOTES_TRG1 "
			+ "AFTER INSERT ON REFAPP.NOTES REFERENCING NEW ROW AS NEWROW FOR EACH ROW BEGIN ATOMIC "
			+ "INSERT INTO REFAPP.NOTE_STATUS (NOTE_ID, STATUS, CREATED, MODIFIED) "
			+ "VALUES (NEWROW.ID, 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); END";

	static final String CREATE_TRIGGER_NOTES_TRG2_STATEMENT = "CREATE TRIGGER REFAPP.NOTES_TRG2 "
			+ "AFTER UPDATE ON REFAPP.NOTES REFERENCING OLD ROW AS OLDROW FOR EACH ROW BEGIN ATOMIC "
			+ "UPDATE REFAPP.NOTE_STATUS SET MODIFIED = CURRENT_TIMESTAMP WHERE NOTE_ID = OLDROW.ID; END";

	static final String CREATE_TRIGGER_NOTE_DETAILS_TRG1_STATEMENT = "CREATE TRIGGER REFAPP.NOTE_DETAILS_TRG1 "
			+ "AFTER UPDATE ON REFAPP.NOTE_DETAILS REFERENCING OLD ROW AS OLDROW FOR EACH ROW BEGIN ATOMIC "
			+ "UPDATE REFAPP.NOTE_STATUS SET MODIFIED = CURRENT_TIMESTAMP WHERE NOTE_ID = OLDROW.NOTE_ID; END";

	static final String CREATE_TRIGGER_NOTE_STATUS_TRG1_STATEMENT = "CREATE TRIGGER REFAPP.NOTE_STATUS_TRG1 "
			+ "AFTER UPDATE OF STATUS ON REFAPP.NOTE_STATUS REFERENCING OLD ROW AS OLDROW FOR EACH ROW BEGIN ATOMIC "
			+ "UPDATE REFAPP.NOTE_STATUS SET MODIFIED = CURRENT_TIMESTAMP WHERE NOTE_ID = OLDROW.NOTE_ID; END";

	static final String INSERT_REF_USER_STATUS_STATEMENT_1 = "INSERT INTO REFAPP.REF_USER_STATUS "
			+ "VALUES ('PENDING', 'User is pending activation')";

	static final String INSERT_REF_USER_STATUS_STATEMENT_2 = "INSERT INTO REFAPP.REF_USER_STATUS "
			+ "VALUES ('ACTIVE', 'User is active')";

	static final String INSERT_REF_USER_STATUS_STATEMENT_3 = "INSERT INTO REFAPP.REF_USER_STATUS "
			+ "VALUES ('SUSPENDED', 'User is suspended')";

	static final String INSERT_REF_USER_STATUS_STATEMENT_4 = "INSERT INTO REFAPP.REF_USER_STATUS "
			+ "VALUES ('DELETED', 'User has been deleted')";

	static final String INSERT_REF_NOTE_STATUS_STATEMENT = "INSERT INTO REFAPP.REF_NOTE_STATUS "
			+ "VALUES ('NEW', 'New note')," + " ('MODIFIED', 'Note has been modified'),"
			+ " ('DELETED', 'Note has been deleted')";

	static final String INSERT_REF_TASK_STATUS_STATEMENT = "INSERT INTO REFAPP.REF_TASK_STATUS "
			+ "VALUES ('NEW', 'New task')," + " ('MODIFIED', 'Task has been modified'),"
			+ " ('DELETED', 'Task has been deleted')";

	static final String INSERT_REF_GENDER_STATEMENT_1 = "INSERT INTO REFAPP.REF_GENDER " + "VALUES ('MALE', 'Male')";

	static final String INSERT_REF_GENDER_STATEMENT_2 = "INSERT INTO REFAPP.REF_GENDER "
			+ "VALUES ('FEMALE', 'Female')";
}
