-- Sequence definitions

CREATE SEQUENCE REFAPP.USERS_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;

CREATE SEQUENCE REFAPP.USER_DETAILS_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;

CREATE SEQUENCE REFAPP.USER_STATUS_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;

CREATE SEQUENCE REFAPP.USER_PASSWORD_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;

CREATE SEQUENCE REFAPP.USER_ADDRESS_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;

CREATE SEQUENCE REFAPP.NOTES_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;

CREATE SEQUENCE REFAPP.NOTE_DETAILS_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;

CREATE SEQUENCE REFAPP.NOTE_STATUS_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;

CREATE SEQUENCE REFAPP.TASKS_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;

CREATE SEQUENCE REFAPP.TASK_DETAILS_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;

CREATE SEQUENCE REFAPP.TASK_STATUS_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;