-- Sequence definitions

CREATE SEQUENCE REFAPP.AUTHORS_ID_SEQ AS INT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;

CREATE SEQUENCE REFAPP.NOTES_ID_SEQ AS INT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;

CREATE SEQUENCE REFAPP.TASKS_ID_SEQ AS INT START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CYCLE;