-- Clean tables

DROP TABLE REFAPP.TASKS_STATUS;

DROP TABLE REFAPP.TASKS;

DROP TABLE REFAPP.NOTES_STATUS;

DROP TABLE REFAPP.NOTES;

DROP TABLE REFAPP.USERS_STATUS;

DROP TABLE REFAPP.USERS_PASSWORD;

DROP TABLE REFAPP.USERS_ADDRESS;

DROP TABLE REFAPP.USERS;
