-- Clean tables
DROP TABLE REFAPP.TASK_DETAILS;

DROP TABLE REFAPP.TASK_STATUS;

DROP TABLE REFAPP.TASKS;

DROP TABLE REFAPP.NOTE_DETAILS;

DROP TABLE REFAPP.NOTE_STATUS;

DROP TABLE REFAPP.NOTES;

DROP TABLE REFAPP.USER_STATUS;

DROP TABLE REFAPP.USER_PASSWORD;

DROP TABLE REFAPP.USER_ADDRESS;

DROP TABLE REFAPP.USER_DETAILS;

DROP TABLE REFAPP.USERS;
