-- Clean triggers

-- Triggers are dropped automatically when tables are dropped.

-- DROP TRIGGER REFAPP.USERS_TRG1;

-- DROP TRIGGER REFAPP.USERS_TRG2;

-- DROP TRIGGER REFAPP.USER_INFO_TRG1;

-- DROP TRIGGER REFAPP.USER_STATUS_TRG1;

-- DROP TRIGGER REFAPP.USER_PASSWORD_TRG1;

-- DROP TRIGGER REFAPP.USER_ADDRESS_TRG1;