-- Clean triggers

-- Triggers are dropped automatically when tables are dropped.

-- DROP TRIGGER REFAPP.USERS_TRG01;

-- DROP TRIGGER REFAPP.USERS_TRG02;

-- DROP TRIGGER REFAPP.USERS_STATUS_TRG;

-- DROP TRIGGER REFAPP.USERS_PASSWORD_TRG

-- DROP TRIGGER REFAPP.USERS_ADDRESS_TRG