-- Clean triggers

-- Triggers are dropped automatically when tables are dropped.

-- DROP TRIGGER REFAPP.AUTHORS_TRG01;

-- DROP TRIGGER REFAPP.AUTHORS_TRG02;

-- DROP TRIGGER REFAPP.AUTHORS_PASSWORD_TRG

-- DROP TRIGGER REFAPP.AUTHORS_ADDRESS_TRG