-- Clean sequences

DROP SEQUENCE REFAPP.USERS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.USER_DETAILS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.USER_STATUS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.USER_PASSWORD_SEQ RESTRICT;

DROP SEQUENCE REFAPP.USER_ADDRESS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.GROUPS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.GROUP_MEMBERS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.NOTES_SEQ RESTRICT;

DROP SEQUENCE REFAPP.NOTE_DETAILS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.NOTE_STATUS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.TASKS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.TASK_DETAILS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.TASK_STATUS_SEQ RESTRICT;