-- Clean sequences

DROP SEQUENCE REFAPP.USERS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.USER_INFO_SEQ RESTRICT;

DROP SEQUENCE REFAPP.USER_STATUS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.USER_PASSWORD_SEQ RESTRICT;

DROP SEQUENCE REFAPP.USER_ADDRESS_SEQ RESTRICT;

DROP SEQUENCE REFAPP.NOTES_SEQ RESTRICT;

DROP SEQUENCE REFAPP.TASKS_SEQ RESTRICT;