-- Clean tables

DROP TABLE REFAPP.TASKS_STATUS;

DROP TABLE REFAPP.TASKS;

DROP TABLE REFAPP.NOTES_STATUS;

DROP TABLE REFAPP.NOTES;

DROP TABLE REFAPP.AUTHORS_STATUS;

DROP TABLE REFAPP.AUTHORS_PASSWORD;

DROP TABLE REFAPP.AUTHORS_ADDRESS;

DROP TABLE REFAPP.AUTHORS;
