-- Table definitions

CREATE TABLE APP.AUTHOR
(
	USERNAME	VARCHAR(20) NOT NULL,
	REALNAME	VARCHAR(50) NOT NULL,
	EMAIL		VARCHAR(50) NOT NULL,
	CONSTRAINT AUTHOR_PK	PRIMARY KEY (USERNAME),
	CONSTRAINT AUTHOR_UC	UNIQUE (EMAIL)
);

CREATE TABLE APP.AUTHOR_STATUS
(
	AUTHOR		VARCHAR(20) NOT NULL,
	STATUS		VARCHAR(10) NOT NULL,
	CREATED		DATE NOT NULL,
	MODIFIED	DATE NOT NULL,
	CONSTRAINT AUTHOR_STATUS_PK		PRIMARY KEY (AUTHOR),
	CONSTRAINT AUTHOR_STATUS_FK1	FOREIGN KEY (AUTHOR) REFERENCES APP.AUTHOR (USERNAME) ON DELETE CASCADE,
	CONSTRAINT AUTHOR_STATUS_FK2	FOREIGN KEY (STATUS) REFERENCES APP.REF_AUTHOR_STATUS (STATUS),
	CONSTRAINT AUTHOR_STATUS_CC1	CHECK (MODIFIED >= CREATED)
);

CREATE TABLE APP.AUTHOR_PASSWORD
(
	AUTHOR		VARCHAR(20) NOT NULL,
	SALT		VARCHAR(50) NOT NULL,
	PASSWORD	VARCHAR(100) NOT NULL,
	CONSTRAINT AUTHOR_PASSWORD_PK	PRIMARY KEY (AUTHOR),
	CONSTRAINT AUTHOR_PASSWORD_FK1	FOREIGN KEY (AUTHOR) REFERENCES APP.AUTHOR (USERNAME) ON DELETE CASCADE
);

CREATE TABLE APP.NOTES
(
	ID			VARCHAR(50) NOT NULL,
	AUTHOR		VARCHAR(20) NOT NULL,
	TITLE		VARCHAR(100) NOT NULL,
	NOTE		VARCHAR(300),
	CONSTRAINT NOTES_PK		PRIMARY KEY (ID),
	CONSTRAINT NOTES_FK1	FOREIGN KEY (AUTHOR) REFERENCES APP.AUTHOR (USERNAME) ON DELETE CASCADE
);

CREATE TABLE APP.NOTES_STATUS
(
	ID			VARCHAR(50) NOT NULL,
	STATUS		VARCHAR(10) NOT NULL,
	CREATED		DATE NOT NULL,
	MODIFIED	DATE NOT NULL,
	CONSTRAINT NOTES_STATUS_PK	PRIMARY KEY (ID),
	CONSTRAINT NOTES_STATUS_FK1	FOREIGN KEY (STATUS) REFERENCES APP.REF_NOTES_STATUS (STATUS),
	CONSTRAINT NOTES_STATUS_CC1	CHECK (MODIFIED >= CREATED)
);
